#!/usr/bin/env php
<?php

/**
 * @file
 * Stop the development server.
 */

declare(strict_types=1);

namespace QuickstartDevTools;

require_once __DIR__ . '/helpers.php';

$webserver_port = resolve_webserver()['port'];

echo '===============================' . PHP_EOL;
echo '      STOP ENVIRONMENT         ' . PHP_EOL;
echo '===============================' . PHP_EOL;
echo PHP_EOL;

TASK('Stopping previously started services, if any.');
stop_webserver($webserver_port);
sleep(1);
PASS('Services stopped.');

echo PHP_EOL;
echo '===============================' . PHP_EOL;
echo '   ENVIRONMENT STOPPED         ' . PHP_EOL;
echo '===============================' . PHP_EOL;
echo PHP_EOL;
