name: theme-tailwindcss

on:
  push:
    branches:
      - develop

jobs:
  theme_tailwindcss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          check-latest: true

      - name: Update npm 🏗
        run: |
          npm install -g npm
          npm --version
      - name: Cache node_modules 📦
        uses: actions/cache@v4.1.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install frontend dependencies 👨🏻‍💻
        run: cd nuxt && npm install

      - name: Install TailwindCSS 👨🏻‍💻
        run: |
          cd nuxt
          npm install -D @nuxtjs/tailwindcss
          sed -i "s/modules: \[\]/modules: \['@nuxtjs\/tailwindcss\']/g" nuxt.config.js
          npx tailwindcss init

      - name: Commit & Push changes 🛎
        uses: actions-js/push@master
        with:
          branch: 'theme/tailwindcss'
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore(theme-tailwindcss): add tailwindcss'
