#!/bin/bash

## Description: Installs Drupal and configures for DruxtSite.
## Usage: drupal-install
## Example: "ddev drupal-install"

# Install composer dependencies.
composer install

# Install a standard Drupal installation.
drush -y site:install --site-name='quickstart-druxt-site' standard

# Enable the Druxt module.
drush -y pm:enable druxt

# Allow the anonymous user read only access to required Druxt resources.
drush role:perm:add anonymous "access druxt resources"

# Enable the Simple OAuth module for authentication.
drush -y pm:enable simple_oauth

# Configure and generate keys for Simple OAuth.
drush -y config:set simple_oauth.settings public_key ../keys/public.key
drush -y config:set simple_oauth.settings private_key ../keys/private.key
drush simple-oauth:generate-keys ../keys

# Enable authenticated editting via JSON:API.
drush -y config:set jsonapi.settings read_only 0

# Create a Druxt consumer.
drush php-eval '
$consumer = \Drupal\consumers\Entity\Consumer::create([
  "owner_id"     => 1,
  "uuid"         => getenv("OAUTH_CLIENT_ID") ?: \Drupal::service("uuid")->generate(),
  "label"        => "Druxt",
  "description"  => "DruxtJS is a bridge between frameworks, Drupal in the back, Nuxt in the front.\n\nhttps://druxtjs.org",
  "confidential" => FALSE,
  "pkce"         => TRUE,
  "redirect"     => getenv("OAUTH_CALLBACK") ?: "http://localhost:3000/callback",
  "image_styles" => [],
  "roles"        => [],
]);
$consumer->save();
'

# Login.
drush user:login
